BanXeMoTo/BanXeMoTo/Areas/Admin/Controllers/OrderController.cs
using BanXeMoTo.Areas.Admin.Models;
using BanXeMoTo.Common;
using Models.DAO;
using Models.EF;
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanXeMoTo.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        private AdminDao dao = new AdminDao();

        // GET: Admin/Order
        public ActionResult Index(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDangDat();
            }
            else
            {
                model = dao.ListDonHangDangDat(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDangDat().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Shipping(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDangVanChuyen();
            }
            else
            {
                model = dao.ListDonHangDangVanChuyen(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDangVanChuyen().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Allorder(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHang();
            }
            else
            {
                model = dao.ListDonHang(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHang().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Donnhan(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDaNhan();
            }
            else
            {
                model = dao.ListDonHangDaNhan(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDaNhan().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Donhuy(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDaHuy();
            }
            else
            {
                model = dao.ListDonHangDaHuy(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDaHuy().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Details(string madonhang)
        {
            DonHang model = dao.InfoDonHang(madonhang);
            if (model != null || string.IsNullOrEmpty(madonhang))
            {
                ArrayList dh = new ArrayList();
                var chitietdonhang = dao.ListChiTietDonHang(madonhang);
                foreach (var item in chitietdonhang)
                {
                    var sanpham = dao.InfoSanPham(item.maSP);
                    CartModel ca = new CartModel()
                    {
                        MaSP = sanpham.maSP,
                        TenSP = sanpham.tenSP,
                        MauSac = item.mauSac,
                        GiaBan = item.thanhTien,
                        AnhSP = sanpham.anhSP
                    };
                    dh.Add(ca);
                }
                ViewBag.ChiTietDonHang = dh;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(string madonhang, string trangthai, string lydo)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            DonHang model = dao.InfoDonHang(madonhang);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            LoginModel session = (LoginModel)Session[Constants.ADMIN_SESSION];
            if (session != null)
            {
                bool result = dao.UpdateDonHang(madonhang, trangthai, lydo, session.MaNV);
                if (result)
                {
                    SetAlert("Cập nhật đơn hàng thành công!", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    SetAlert("Cập nhật đơn hàng thất bại!", "danger");
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Danhanhang(string madonhang)
        {
            if (QuyenNVBH())
            {
                return RedirectToAction("Index", "Home");
            }
            DonHang model = dao.InfoDonHang(madonhang);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            LoginModel session = (LoginModel)Session[Constants.ADMIN_SESSION];
            if (session != null)
            {
                bool result = dao.XacNhanDonHangDaNhan(madonhang, session.MaNV);
                if (result)
                {
                    SetAlert("Cập nhật đơn hàng thành công!", "success");
                }
                else
                {
                    SetAlert("Cập nhật đơn hàng thất bại!", "danger");
                }
            }
            return RedirectToAction("Details", new { madonhang });
        }

    }
}

BanXeMoTo/BanXeMoTo/Controllers/SanphamController.cs
using BanXeMoTo.Common;
using BanXeMoTo.Models;
using Models.DAO;
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanXeMoTo.Controllers
{
    public class SanphamController : TbController
    {
        private UserDao dao = new UserDao();

        // GET: Sanpham
        public ActionResult Index(int page = 1, int pagesize = 15)
        {
            var model = dao.ListSanPhamAutoUpdate();
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Search(string searchString, int page = 1, int pagesize = 15)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                ThongBao("Hãy nhập tên sản phẩm", "warning");
                return RedirectToAction("Index");
            }
            else
            {
                var model = dao.ListWhereSanPhamAll(searchString);
                if (model.Count == 0)
                {
                    ThongBao("Không tìm thấy sản phẩm \"" + searchString + "\"", "warning");
                    return RedirectToAction("Index");
                }
                ViewBag.SearchString = searchString;
                return View(model.ToPagedList(page, pagesize));
            }
        }

        public ActionResult Details(string masanpham, string mausacchon)
        {
            SanPham model = dao.InfoSanPham(masanpham);
            if (model == null || string.IsNullOrEmpty(masanpham))
            {
                return RedirectToAction("Index");
            }
            dao.TangLuotXem(masanpham);
            ViewBag.SoLuong = dao.TinhSoLuong(masanpham);
            ViewBag.DanhGia = dao.TinhTiLeDanhGia(masanpham);
            ViewBag.MauSac = dao.LayMauSac(masanpham);

            ViewBag.XemNhieu = dao.ListXemNhieu();
            ViewBag.MuaNhieu = dao.ListMuaNhieu();

            ViewBag.BinhLuanDanhGia = dao.BinhLuanDanhGia(masanpham);
            ViewBag.CountBLDG = dao.BinhLuanDanhGia(masanpham).Count();

            if (!string.IsNullOrEmpty(mausacchon))
            {
                ViewBag.MauSacChon = mausacchon;
                decimal? giamausacchon = dao.LayGiaThongTinSanPham(mausacchon).giaBan;
                model.giaBan = String.Format("{0:0,0 VNĐ}", giamausacchon);
            }

            var session = (LoginModel)Session[Constants.USER_SESSION];
            if (session != null)
            {
                ViewBag.KTMH = dao.KiemTraMuaHang(session.MaKH, masanpham);
            }
            else
            {
                ViewBag.KTMH = 2;
            }
            return View(model);
        }

        public ActionResult Danhgia(string masanpham, string sosaodanhgia, string noidungbinhluan)
        {
            LoginModel session = (LoginModel)Session[Constants.USER_SESSION];
            if (session != null)
            {
                var danhgia = new BinhLuanDanhGia();
                danhgia.maKH = session.MaKH;
                danhgia.maSP = masanpham;
                danhgia.soSaoDanhGia = sosaodanhgia;
                danhgia.noiDungBinhLuan = noidungbinhluan;
                danhgia.ngayDanhGia = DateTime.Now;

                var dg = dao.TaiBinhLuanDanhGia(danhgia);
                if (dg == 1)
                {
                    ThongBao("Đã đăng tải bình luận thành công", "success");
                }
                else if (dg == 2)
                {
                    ThongBao("Cập nhật nhận xét thành công", "success");
                }
                else
                {
                    ThongBao("Không thể đánh giá", "error");
                }
            }
            return RedirectToAction("Details", "SanPham", new { masanpham });
        }

        public ActionResult Honda(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("HD");
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Yamaha(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("YA");
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Kawasaki(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("KA");
            return View(model.ToPagedList(page, pagesize));
        }

    }
}

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Order/Allorder.cshtml
@using PagedList.Mvc
@using PagedList
@model PagedList.IPagedList<Models.EF.DonHang>

@{
    ViewBag.Title = "Tất cả đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.DonHang = "active active-link";
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Danh sách tất cả đơn hàng (@ViewBag.SoLuong đơn)</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        @using (Html.BeginForm("Allorder", "Order", FormMethod.Get))
        {
            <div class="input-group mar-btm">
                <input type="text" placeholder="Search..." class="form-control h-auto" name="searchString" value="@ViewBag.searchString" />
                <span class="input-group-btn">
                    <button class="btn btn-danger btn-labeled fa fa-search" type="submit">Tìm kiếm</button>
                </span>
            </div>
        }
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <colgroup>
                    <col width="1" />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col width="1" />
                </colgroup>
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn hàng</th>
                        <th>Tên khách hàng</th>
                        <th>Ngày đặt hàng</th>
                        <th>Số lượng</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int i = 1; }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@i</td>
                            <td>@item.maDH</td>
                            <td>@item.KhachHang.tenKH</td>
                            <td>@String.Format("{0:dd/MM/yyyy}", item.ngayDatHang)</td>
                            <td>@item.tongSoLuong</td>
                            <td>@String.Format("{0:0,0 VNĐ}", item.tongTien)</td>
                            <td class="text-danger text-bold">@item.trangThai</td>
                            <td>
                                <a href="@Url.Action("Details","Order", new { @madonhang = item.maDH })" class="btn btn-warning btn-sm btn-labeled fa fa-info">Chi tiết</a>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
            <!--Pagination-->
            <p class="col-sm-12">Tổng số @ViewBag.Tong - Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</p>
            @Html.PagedListPager(Model, page => Url.Action("Allorder", new { @searchString = ViewBag.searchString, page }))
            <!--End Default Pagination-->
        </div>
    </div>
</div>

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Order/Details.cshtml
@model Models.EF.DonHang

@{
    ViewBag.Title = "Đơn hàng đang vận chuyển";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.DonHang = "active active-link";
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Chi tiết đơn hàng: @Model.maDH</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        <div class="table-responsive">
            <table class="table table-hover table-vcenter">
                <colgroup>
                    <col width="1" />
                    <col />
                    <col />
                    <col />
                    <col />
                </colgroup>
                <thead>
                    <tr>
                        <th colspan="2" class="text-left">Mã đơn hàng: @Model.maDH</th>
                        <th colspan="3" class="text-right">Tình trạng: <span class="text-bold text-danger"><i>@Model.trangThai</i></span></th>
                    </tr>
                    @if (Model.trangThai == "Đã hủy")
                    {
                        <tr>
                            <th>Lý do hủy</th>
                            <td colspan="4"><em>@Model.lyDo</em></td>
                        </tr>
                    }
                    <tr>
                        <th class="t-center">&nbsp;</th>
                        <th>Tên sản phẩm</th>
                        <th class="t-center">Màu sắc</th>
                        <th class="t-center">Số lượng</th>
                        <th class="t-center">Giá bán</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="4">Tổng phụ</th>
                        <th class="text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongPhu)</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in ViewBag.ChiTietDonHang)
                    {
                        <tr>
                            <td><a href="@Url.Action("Details", "Sanpham", new { @masanpham = item.MaSP })"><img width="70" src="~/Assets/user/products-images/@item.AnhSP"></a></td>
                            <td><a href="@Url.Action("Details", "Sanpham", new { @masanpham = item.MaSP })">@item.TenSP</a></td>
                            <td>@item.MauSac</td>
                            <td>
                                <input type="text" class="input-text qty" value="1" disabled />
                            </td>
                            <td><span class="cart-price"><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", item.GiaBan)</span></span></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <h4>Thông tin người nhận</h4>
        <div class="table-responsive">
            <table class="table table-bordered">
                <colgroup>
                    <col />
                    <col />
                </colgroup>
                <tfoot>
                    <tr style="border-top: 2px solid #eaeaea">
                        <td><strong>Tổng cộng</strong></td>
                        <td><strong><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongTien)</span></strong></td>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td>Tên người nhận</td>
                        <td><span class="">@Model.KhachHang.tenKH</span></td>
                    </tr>
                    <tr>
                        <td>SĐT người nhận</td>
                        <td><span class="">@Model.KhachHang.SDT</span></td>
                    </tr>
                    <tr>
                        <td>Ngày đặt hàng</td>
                        <td><span class="">@String.Format("{0:dd/MM/yyyy}", Model.ngayDatHang)</span></td>
                    </tr>
                    <tr>
                        <td>Ngày giao hàng dự kiến</td>
                        <td><span class="">@String.Format("{0:dd/MM/yyyy}", Model.ngayGiaoHang)</span></td>
                    </tr>
                    <tr>
                        <td>Ngày thanh toán</td>
                        <td><span class="">@String.Format("{0:dd/MM/yyyy}", Model.ngayThanhToan)</span></td>
                    </tr>
                    <tr>
                        <td>Địa chỉ giao hàng</td>
                        <td><span class="">@Model.diaChiGiaoHang</span></td>
                    </tr>
                    <tr>
                        <td>Tổng phụ</td>
                        <td><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongPhu)</span></td>
                    </tr>
                    <tr>
                        <td>Khuyến mãi</td>
                        <td><span class="">@Model.tongSoLuong%</span></td>
                    </tr>
                    <tr>
                        <td>Đã giảm</td>
                        <td><span class="text-bold text-danger">@String.Format("- {0:0,0 VNĐ}", Model.tongGiam)</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-9 col-sm-offset-3">
                    @using (Html.BeginForm("Update", "Order", FormMethod.Post))
                    {
                        if (Model.trangThai.Contains("Đang vận chuyển"))
                        {
                            <a href="@Url.Action("Danhanhang","Order", new { @madonhang = Model.maDH })" onclick="if (confirm('Xác nhận đơn hàng đã được nhận!') == false) return false;" class="btn btn-success btn-labeled fa fa-check">Đã nhận hàng</a>
                            <input name="madonhang" value="@Model.maDH" type="hidden" />
                            <input name="trangthai" value="2" type="hidden" />
                            <input name="lydo" value="Khách hàng không nhận hàng" type="hidden" />
                            <button type="submit" onclick="if (confirm('Xác nhận đơn hàng bị từ chối nhận!') == false) return false;" class="btn btn-dark btn-labeled fa fa-check mar-rgt">Không nhận hàng</button>
                        }
                        <a href="@Url.Action("Index","Order")" class="btn btn-danger btn-labeled fa fa-close">Quay về</a>
                        <a href="" class="btn btn-mint btn-labeled fa fa-download mar-lft" id="doPrint">In hóa đơn</a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row hidden">
    <div id="printDiv" class="panel col-sm-12 col-md-10 col-lg-8 col-xl-6">
        <div class="panel-heading">
            <h3 class="panel-title">Đơn hàng: @Model.maDH</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>Tên sản phẩm</th>
                            <th class="t-center">Màu sắc</th>
                            <th class="t-center">Số lượng</th>
                            <th class="t-center">Giá bán</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th colspan="3">Tổng phụ</th>
                            <th class="text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongPhu)</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in ViewBag.ChiTietDonHang)
                        {
                            <tr>
                                <td>@item.TenSP</td>
                                <td>@item.MauSac</td>
                                <td>1</td>
                                <td><span class="cart-price"><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", item.GiaBan)</span></span></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <h4>Thông tin người nhận</h4>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <colgroup>
                        <col />
                        <col />
                    </colgroup>
                    <tfoot>
                        <tr style="border-top: 2px solid #eaeaea">
                            <td><strong>Tổng cộng</strong></td>
                            <td><strong><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongTien)</span></strong></td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>Tên người nhận</td>
                            <td><span class="">@Model.KhachHang.tenKH</span></td>
                        </tr>
                        <tr>
                            <td>SĐT người nhận</td>
                            <td><span class="">@Model.KhachHang.SDT</span></td>
                        </tr>
                        <tr>
                            <td>Ngày đặt hàng</td>
                            <td><span class="">@String.Format("{0:dd/MM/yyyy}", Model.ngayDatHang)</span></td>
                        </tr>
                        <tr>
                            <td>Địa chỉ giao hàng</td>
                            <td><span class="">@Model.diaChiGiaoHang</span></td>
                        </tr>
                        <tr>
                            <td>Tổng phụ</td>
                            <td><span class="text-bold text-danger">@String.Format("{0:0,0 VNĐ}", Model.tongPhu)</span></td>
                        </tr>
                        <tr>
                            <td>Khuyến mãi</td>
                            <td><span class="">@Model.tongSoLuong%</span></td>
                        </tr>
                        <tr>
                            <td>Đã giảm</td>
                            <td><span class="text-bold text-danger">@String.Format("- {0:0,0 VNĐ}", Model.tongGiam)</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel-footer">
            <div class="text-center">
                <p>
                    <img src="~/Assets/favicon.png" width="30" />
                    <span>Cảm ơn bạn đã giao dịch với chúng tôi</span>
                </p>
            </div>
        </div>
    </div>
</div>

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Order/Donhuy.cshtml
@using PagedList.Mvc
@using PagedList
@model PagedList.IPagedList<Models.EF.DonHang>

@{
    ViewBag.Title = "Đơn hàng đã hủy";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.DonHang = "active active-link";
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Danh sách đơn hàng đã hủy (@ViewBag.SoLuong đơn)</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        @using (Html.BeginForm("Donhuy", "Order", FormMethod.Get))
        {
            <div class="input-group mar-btm">
                <input type="text" placeholder="Search..." class="form-control h-auto" name="searchString" value="@ViewBag.searchString" />
                <span class="input-group-btn">
                    <button class="btn btn-danger btn-labeled fa fa-search" type="submit">Tìm kiếm</button>
                </span>
            </div>
        }
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <colgroup>
                    <col width="1" />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col />
                    <col width="1" />
                </colgroup>
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Mã đơn hàng</th>
                        <th>Tên khách hàng</th>
                        <th>Ngày đặt hàng</th>
                        <th>Số lượng</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái</th>
                        <th>Lý do</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int i = 1; }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@i</td>
                            <td>@item.maDH</td>
                            <td>@item.KhachHang.tenKH</td>
                            <td>@String.Format("{0:dd/MM/yyyy}", item.ngayDatHang)</td>
                            <td>@item.tongSoLuong</td>
                            <td>@String.Format("{0:0,0 VNĐ}", item.tongTien)</td>
                            <td class="text-danger text-bold">@item.trangThai</td>
                            <td><em>@item.lyDo</em></td>
                            <td>
                                <a href="@Url.Action("Details","Order", new { @madonhang = item.maDH })" class="btn btn-warning btn-sm btn-labeled fa fa-info">Chi tiết</a>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
            <!--Pagination-->
            <p class="col-sm-12">Tổng số @ViewBag.Tong - Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</p>
            @Html.PagedListPager(Model, page => Url.Action("Donhuy", new { @searchString = ViewBag.searchString, page }))
            <!--End Default Pagination-->
        </div>
    </div>
</div>