BanXeMoTo/BanXeMoTo/Controllers/SignupController.cs
using BanXeMoTo.Common;
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanXeMoTo.Controllers
{
    public class SignupController : TbController
    {
        private UserDao dao = new UserDao();

        // GET: Signup
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(KhachHang model, int year, int month, int day)
        {
            if (ModelState.IsValid)
            {
                string makhachhang = dao.TaoMaKhachHang();

                model.maKH = makhachhang;
                model.nickName = model.matKhau;
                model.matKhau = Encryptor.EncryptMD5(model.matKhau);
                DateTime ngaysinh = new DateTime(year, month, day);
                model.ngaySinh = ngaysinh;
                model.tienThuong = 0;

                KhachHang ktsdt = dao.InfoKhachHang(model.SDT);
                KhachHang ktemail = dao.InfoKhachHang(model.Email);
                if (ktsdt != null || ktemail != null)
                {
                    TempData["AlertType"] = "alert-danger";
                    TempData["AlertMessage"] = "Số điện thoại hoặc Email này đã được đăng ký!";

                    ThongBao("Đăng ký thất bại", "error");
                    ThongBao("Hãy kiểm tra lại Số điện thoại hoặc Email", "warning");
                }
                else
                {
                    bool result = dao.Insert(model);
                    if (result)
                    {
                        TempData["AlertType"] = "alert-success";
                        TempData["AlertMessage"] = "Đăng ký thành công! Giờ bạn có thể đăng nhập";

                        ThongBao("Đăng ký thành công", "success");
                        return RedirectToAction("Index", "Login");
                    }
                    else
                    {
                        TempData["AlertType"] = "alert-danger";
                        TempData["AlertMessage"] = "Đăng ký thất bại! Hãy kiểm tra lại thông tin";

                        ThongBao("Đăng ký thất bại", "error");
                        ThongBao("Hãy kiểm tra lại thông tin", "warning");
                    }
                }
            }
            return View("Index");
        }
    }
}

BanXeMoTo/BanXeMoTo/Views/Signup/Index.cshtml
@model Models.EF.KhachHang

@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="main-container col1-layout">
    <div class="main container">
        <div class="account-login">
            <div class="page-title">
                <h2>Tạo một tài khoản</h2>
            </div>
            <fieldset class="col2-set">
                <legend>Tạo một tài khoản</legend>
                <div class="col-1 new-users">
                    <strong>Những khách đã có tài khoản</strong>
                    <div class="content">
                        <p>Bằng cách đăng nhập tài khoản vào cửa hàng của chúng tôi, bạn sẽ có thể chuyển qua quy trình thanh toán nhanh hơn, lưu trữ nhiều địa chỉ giao hàng, xem và theo dõi đơn hàng của bạn trong tài khoản của bạn và hơn thế nữa.</p>
                        <div class="buttons-set">
                            <a href="@Url.Action("Index","Login")"><button class="button create-account" type="button"><span>Đăng nhập tài khoản</span></button></a>
                        </div>
                    </div>
                </div>
                <div class="col-2 registered-users">
                    <strong>Đăng ký một tài khoản</strong>
                    <div class="content">
                        @if (TempData["AlertMessage"] != null)
                        {
                            <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                                @TempData["AlertMessage"]
                            </div>
                        }
                        @using (Html.BeginForm("Index", "Signup", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <ul class="form-list">
                                <li>
                                    <label for="tenkh">Họ và tên <span class="required">*</span></label>
                                    <br>
                                    @Html.TextBoxFor(model => model.tenKH, new { @type = "text", @id = "tenkh", @class = "input-text required-entry", @placeholder = "Nhập họ và tên", @required = "" })
                                    @Html.ValidationMessageFor(model => model.tenKH, "", new { @class = "text-danger" })
                                </li>
                                <li>
                                    <script src="~/Assets/user/js/jquery-latest.js"></script>
                                    <script>
                                        $(function () {
                                            //Năm tự động điền vào select
                                            var seYear = $('#year');
                                            var date = new Date();
                                            var cur = date.getFullYear();

                                            seYear.append('<option value="">-- Năm --</option>');
                                            for (i = cur; i >= cur - 100; i--) {
                                                seYear.append('<option value="' + i + '">' + i + '</option>');
                                            };

                                            //Tháng tự động điền vào select
                                            var seMonth = $('#month');
                                            var date = new Date();

                                            var month = new Array();
                                            month[1] = "Tháng 01";
                                            month[2] = "Tháng 02";
                                            month[3] = "Tháng 03";
                                            month[4] = "Tháng 04";
                                            month[5] = "Tháng 05";
                                            month[6] = "Tháng 06";
                                            month[7] = "Tháng 07";
                                            month[8] = "Tháng 08";
                                            month[9] = "Tháng 09";
                                            month[10] = "Tháng 10";
                                            month[11] = "Tháng 11";
                                            month[12] = "Tháng 12";

                                            seMonth.append('<option value="">-- Tháng --</option>');
                                            for (i = 1; i <= 12; i++) {
                                                seMonth.append('<option value="' + i + '">' + month[i] + '</option>');
                                            };

                                            //Ngày tự động điền vào select
                                            function dayList(month, year) {
                                                var day = new Date(year, month, 0);
                                                return day.getDate();
                                            }

                                            $('#year, #month').change(function () {
                                                //Đoạn code lấy id không viết bằng jQuery để phù hợp với đoạn code bên dưới
                                                var y = document.getElementById('year');
                                                var m = document.getElementById('month');
                                                var d = document.getElementById('day');

                                                var year = y.options[y.selectedIndex].value;
                                                var month = m.options[m.selectedIndex].value;
                                                var day = d.options[d.selectedIndex].value;
                                                if (day == ' ') {
                                                    var days = (year == ' ' || month == ' ') ? 31 : dayList(month, year);
                                                    d.options.length = 0;
                                                    d.options[d.options.length] = new Option('-- Ngày --', ' ');
                                                    for (var i = 1; i <= days; i++)
                                                        d.options[d.options.length] = new Option(i, i);
                                                }
                                            });
                                        });
                                    </script>

                                    <label>Ngày sinh <span class="required">*</span></label>
                                    <br>
                                    <select style="background-color:#fff;width:auto;" name="year" id="year" size="1" required=""></select>
                                    <select style="background-color:#fff;width:auto;" name="month" id="month" size="1" required=""></select>
                                    <select style="background-color:#fff;width:auto;" name="day" id="day" size="1" required="">
                                        <option value=" " selected="selected">-- Ngày --</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.ngaySinh, "", new { @class = "text-danger" })
                                </li>
                                <li>
                                    <label>Giới tính <span class="required">*</span></label>
                                    <br>
                                    <div style="margin:10px 10px 20px 10px">
                                        @Html.RadioButtonFor(model => model.gioiTinh, "1", new { @id = "nam", @class = "radio", @required = "" })
                                        <label class="m-r-10" for="nam">Nam</label>
                                        @Html.RadioButtonFor(model => model.gioiTinh, "0", new { @id = "nu", @class = "radio", @required = "" })
                                        <label class="m-r-10" for="nam">Nữ</label>
                                        @Html.RadioButtonFor(model => model.gioiTinh, "2", new { @id = "khac", @class = "radio", @required = "" })
                                        <label for="nam">Khác</label>
                                        @Html.ValidationMessageFor(model => model.gioiTinh, "", new { @class = "text-danger" })
                                    </div>
                                </li>
                                <li>
                                    <label for="sdt">Số điện thoại <span class="required">*</span></label>
                                    <br>
                                    @Html.TextBoxFor(model => model.SDT, new { @id = "sdt", @class = "input-text required-entry", @placeholder = "Nhập số điện thoại", @required = "" })
                                    @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                                </li>
                                <li>
                                    <label for="email">Email <span class="required">*</span></label>
                                    <br>
                                    @Html.TextBoxFor(model => model.Email, new { @type = "email", @id = "email", @class = "input-text required-entry", @placeholder = "Nhập email", @required = "" })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </li>
                                <li>
                                    <label for="pass">Mật khẩu <span class="required">*</span></label>
                                    <br>
                                    @Html.TextBoxFor(model => model.matKhau, new { @type = "password", @id = "pass", @class = "input-text required-entry", @placeholder = "Nhập mật khẩu", @required = "" })
                                    @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
                                </li>
                            </ul>
                            <p class="required">* Phần bắt buộc</p>
                            <div class="buttons-set">
                                <button type="submit" class="button login"><span>Đăng ký</span></button>
                                <a class="forgot-word" href="">Đã có tài khoản?</a>
                            </div>
                        }
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</section>