BanXeMoTo/BanXeMoTo/Areas/Admin/Controllers/KhohangController.cs
using BanXeMoTo.Areas.Admin.Models;
using BanXeMoTo.Common;
using Models.DAO;
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanXeMoTo.Areas.Admin.Controllers
{
    public class KhohangController : BaseController
    {
        private AdminDao dao = new AdminDao();

        // GET: Admin/Khohang
        public ActionResult Index()
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Nhapkho(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<PhieuNhap> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListPhieuNhap();
                foreach (var item in model)
                {
                    dao.TinhSoLuongPhieuNhap(item.maPN);
                }
            }
            else
            {
                model = dao.ListPhieuNhap(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListPhieuNhap().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Detailspn(string maphieunhap)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            PhieuNhap model = dao.InfoPhieuNhap(maphieunhap);
            if (model == null)
            {
                return RedirectToAction("Nhapkho");
            }
            ViewBag.NgayNhap = String.Format("{0:dd/MM/yyyy}", DateTime.Now);
            return View(model);
        }

        public ActionResult Detailspx(string madonhang)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var model = dao.InfoDonHang(madonhang);
            if (model == null)
            {
                return RedirectToAction("Xuatkho");
            }
            return View(model);
        }

        public ActionResult Create()
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listncc = dao.DanhSachNhaCungCap();
            ViewBag.ListNhaCungCap = new SelectList(Listncc, "maNCC", "tenNCC");
            ViewBag.MaPhieuNhap = dao.TaoMaPhieuNhap();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PhieuNhap phieunhap)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listncc = dao.DanhSachNhaCungCap();
            ViewBag.ListNhaCungCap = new SelectList(Listncc, "maNCC", "tenNCC");
            ViewBag.MaPhieuNhap = dao.TaoMaPhieuNhap();
            LoginModel session = (LoginModel)Session[Constants.ADMIN_SESSION];
            if (ModelState.IsValid)
            {
                phieunhap.maPN = ViewBag.MaPhieuNhap;
                phieunhap.maNV = session.MaNV;
                phieunhap.ngayNhap = DateTime.Now;
                bool model = dao.InsertPhieuNhap(phieunhap);
                if (model)
                {
                    SetAlert("Thành công, hãy nhập thông tin sản phẩm", "success");
                    return RedirectToAction("Createttsp", new { @maphieunhap = phieunhap.maPN });
                }
                else
                {
                    SetAlert("Thêm thất bại! Hãy kiểm tra lại thông tin", "danger");
                }
            }
            return View(phieunhap);
        }

        public ActionResult Createttsp(string maphieunhap)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listsp = dao.ListSanPham();
            ViewBag.ListSanPham = new SelectList(Listsp, "maSP", "tenSP");
            ViewBag.MaPhieuNhap = maphieunhap;
            ViewBag.MaTTSP = dao.TaoMaThongTinSanPham();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Createttsp(ThongTinSanPham ttsp, string luuvaket)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listsp = dao.ListSanPham();
            ViewBag.ListSanPham = new SelectList(Listsp, "maSP", "tenSP");
            ViewBag.MaPhieuNhap = ttsp.maPN;

            if (ModelState.IsValid)
            {
                ttsp.maTTSP = dao.TaoMaThongTinSanPham();
                string result = dao.InsertThongTinSanPham(ttsp);
                if (result.Equals("done"))
                {
                    dao.TinhTienPhieuNhap(ttsp.maPN);
                    SetAlert("Thêm sản phẩm thành công", "success");
                    if (luuvaket != null)
                    {
                        return RedirectToAction("Nhapkho");
                    }
                    return RedirectToAction("Createttsp");
                }
                else
                {
                    SetAlert(ThongBaoLoi(result), "danger");
                }
            }
            return View(ttsp);
        }

        public ActionResult Xuatkho(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDaXuatKho();
            }
            else
            {
                model = dao.ListDonHangDaXuatKho(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDaXuatKho().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Xuatttsp(string searchString, int page = 1, int pagesize = 10)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            List<DonHang> model;
            if (string.IsNullOrEmpty(searchString))
            {
                model = dao.ListDonHangDaXacNhan();
            }
            else
            {
                model = dao.ListDonHangDaXacNhan(searchString);
                if (model.Count == 0)
                {
                    SetAlert("Không tìm thấy đơn hàng " + searchString, "warning");
                }
            }
            ViewBag.Tong = model.Count();
            ViewBag.SoLuong = dao.ListDonHangDaXacNhan().Count();
            ViewBag.searchString = searchString;
            return View(model.ToPagedList(page, pagesize));
        }

        [HttpPost]
        public ActionResult Xacnhan(string madonhang)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            DonHang model = dao.InfoDonHang(madonhang);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            LoginModel session = (LoginModel)Session[Constants.ADMIN_SESSION];
            if (session != null)
            {
                bool result = dao.XacNhanXuatDonHang(madonhang, session.MaNV);
                if (result)
                {
                    SetAlert("Cập nhật đơn hàng thành công!", "success");
                    return RedirectToAction("Xuatttsp");
                }
                else
                {
                    SetAlert("Cập nhật đơn hàng thất bại!", "danger");
                }
            }
            return RedirectToAction("Xuatttsp");
        }

        public ActionResult Updatepn(string mattsp)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listsp = dao.ListSanPham();
            ViewBag.ListSanPham = new SelectList(Listsp, "maSP", "tenSP");
            ThongTinSanPham model = dao.InfoThongTinSanPham(mattsp);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Updatepn(ThongTinSanPham ttsp)
        {
            if (QuyenNVKH())
            {
                return RedirectToAction("Index", "Home");
            }
            var Listsp = dao.ListSanPham();
            ViewBag.ListSanPham = new SelectList(Listsp, "maSP", "tenSP");
            if (ModelState.IsValid)
            {
                ThongTinSanPham model = dao.InfoThongTinSanPham(ttsp.maTTSP);
                if (model == null)
                {
                    return RedirectToAction("Index");
                }
                bool result = dao.UpdateThongTinSanPhamPN(ttsp);
                if (result)
                {
                    dao.TinhTienPhieuNhap(model.maPN);
                    SetAlert("Cập nhật thông tin sản phẩm thành công!", "success");
                    return RedirectToAction("Detailspn", new { @maphieunhap = model.maPN });
                }
                else
                {

BanXeMoTo/BanXeMoTo/Controllers/SanphamController.cs
using BanXeMoTo.Common;
using BanXeMoTo.Models;
using Models.DAO;
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanXeMoTo.Controllers
{
    public class SanphamController : TbController
    {
        private UserDao dao = new UserDao();

        // GET: Sanpham
        public ActionResult Index(int page = 1, int pagesize = 15)
        {
            var model = dao.ListSanPhamAutoUpdate();
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Search(string searchString, int page = 1, int pagesize = 15)
        {
            if (string.IsNullOrEmpty(searchString))
            {
                ThongBao("Hãy nhập tên sản phẩm", "warning");
                return RedirectToAction("Index");
            }
            else
            {
                var model = dao.ListWhereSanPhamAll(searchString);
                if (model.Count == 0)
                {
                    ThongBao("Không tìm thấy sản phẩm \"" + searchString + "\"", "warning");
                    return RedirectToAction("Index");
                }
                ViewBag.SearchString = searchString;
                return View(model.ToPagedList(page, pagesize));
            }
        }

        public ActionResult Details(string masanpham, string mausacchon)
        {
            SanPham model = dao.InfoSanPham(masanpham);
            if (model == null || string.IsNullOrEmpty(masanpham))
            {
                return RedirectToAction("Index");
            }
            dao.TangLuotXem(masanpham);
            ViewBag.SoLuong = dao.TinhSoLuong(masanpham);
            ViewBag.DanhGia = dao.TinhTiLeDanhGia(masanpham);
            ViewBag.MauSac = dao.LayMauSac(masanpham);

            ViewBag.XemNhieu = dao.ListXemNhieu();
            ViewBag.MuaNhieu = dao.ListMuaNhieu();

            ViewBag.BinhLuanDanhGia = dao.BinhLuanDanhGia(masanpham);
            ViewBag.CountBLDG = dao.BinhLuanDanhGia(masanpham).Count();

            if (!string.IsNullOrEmpty(mausacchon))
            {
                ViewBag.MauSacChon = mausacchon;
                decimal? giamausacchon = dao.LayGiaThongTinSanPham(mausacchon).giaBan;
                model.giaBan = String.Format("{0:0,0 VNĐ}", giamausacchon);
            }

            var session = (LoginModel)Session[Constants.USER_SESSION];
            if (session != null)
            {
                ViewBag.KTMH = dao.KiemTraMuaHang(session.MaKH, masanpham);
            }
            else
            {
                ViewBag.KTMH = 2;
            }
            return View(model);
        }

        public ActionResult Danhgia(string masanpham, string sosaodanhgia, string noidungbinhluan)
        {
            LoginModel session = (LoginModel)Session[Constants.USER_SESSION];
            if (session != null)
            {
                var danhgia = new BinhLuanDanhGia();
                danhgia.maKH = session.MaKH;
                danhgia.maSP = masanpham;
                danhgia.soSaoDanhGia = sosaodanhgia;
                danhgia.noiDungBinhLuan = noidungbinhluan;
                danhgia.ngayDanhGia = DateTime.Now;

                var dg = dao.TaiBinhLuanDanhGia(danhgia);
                if (dg == 1)
                {
                    ThongBao("Đã đăng tải bình luận thành công", "success");
                }
                else if (dg == 2)
                {
                    ThongBao("Cập nhật nhận xét thành công", "success");
                }
                else
                {
                    ThongBao("Không thể đánh giá", "error");
                }
            }
            return RedirectToAction("Details", "SanPham", new { masanpham });
        }

        public ActionResult Honda(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("HD");
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Yamaha(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("YA");
            return View(model.ToPagedList(page, pagesize));
        }

        public ActionResult Kawasaki(string loaisp, int page = 1, int pagesize = 15)
        {
            if (!string.IsNullOrEmpty(loaisp))
            {
                var model1 = dao.ListLoaiSanPhamAll(loaisp);
                ViewBag.Category = model1.FirstOrDefault().LoaiSanPham.tenLSP;

                return View(model1.ToPagedList(page, pagesize));
            }

            var model = dao.ListSanPhamHSX("KA");
            return View(model.ToPagedList(page, pagesize));
        }

    }
}

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Khohang/Create.cshtml
@using BanXeMoTo.Areas.Admin.Models
@using BanXeMoTo.Common
@model Models.EF.PhieuNhap

@{
    ViewBag.Title = "Thêm phiếu nhập";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.NhapSanPham = "active active-link";
}

@{
    var session = (LoginModel)Session[Constants.ADMIN_SESSION];
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Thêm phiếu nhập mới</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        <!-- BASIC FORM ELEMENTS -->
        @using (Html.BeginForm("Create", "Khohang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="panel-body form-horizontal form-padding">
                <div class="form-group">
                    <label class="col-md-3 control-label">Mã phiếu nhập</label>
                    <div class="col-md-9"><p class="form-control-static">@ViewBag.MaPhieuNhap</p></div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Tên nhân viên</label>
                    <div class="col-md-9"><p class="form-control-static">@session.TenNV</p></div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Tên nhà cung cấp</label>
                    <div class="col-md-9">
                        @Html.DropDownListFor(x => x.maNCC, ViewBag.ListNhaCungCap as SelectList, new { @class = "selectpicker", @data_live_search = "true", @required = "" })
                        @Html.ValidationMessageFor(x => x.maNCC, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label" for="demo-text-input">Ngày nhập</label>
                    <div class="col-md-9"><p class="form-control-static">@string.Format("{0:dd/MM/yyyy}", DateTime.Now)</p></div>
                </div>

                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-9 col-sm-offset-3">
                            <button class="btn btn-success btn-labeled fa fa-check mar-rgt" type="submit" onclick="if (confirm('Bạn có muốn tạo một phiếu nhập mới không?') == false) return false;">Tạo phiếu nhập</button>
                            <a href="@Url.Action("Nhapkho", "Khohang")" class="btn btn-danger btn-labeled fa fa-close">Hủy</a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <!-- END BASIC FORM ELEMENTS -->
    </div>
</div>

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Khohang/Createttsp.cshtml
@model Models.EF.ThongTinSanPham

@{
    ViewBag.Title = "Nhập thông tin sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.NhapSanPham = "active active-link";
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Nhập thông tin sản phẩm</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        @using (Html.BeginForm("Createttsp", "Khohang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <!-- BASIC FORM ELEMENTS -->
            <div class="panel-body form-horizontal form-padding">
                <div class="form-group">
                    <label class="col-md-3 control-label">Mã phiếu nhập</label>
                    <div class="col-md-9"><p class="form-control-static text-bold">@ViewBag.MaPhieuNhap</p></div>
                    @Html.TextBoxFor(x => x.maPN, new { @type = "hidden", @Value = @ViewBag.MaPhieuNhap })
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Mã Thông tin sản phẩm</label>
                    <div class="col-md-9"><p class="form-control-static text-bold">@ViewBag.MaTTSP</p></div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="tensp">Tên sản phẩm <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.DropDownListFor(x => x.maSP, ViewBag.ListSanPham as SelectList, new { @class = "selectpicker", @data_live_search = "true", @id = "tensp", @required = "" })
                        @Html.ValidationMessageFor(x => x.maSP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh1">Số khung <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.soKhung, new { @type = "text", @id = "hinhanh1", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.soKhung, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh2">Số máy <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.soMay, new { @type = "text", @id = "hinhah2", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.soMay, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh3">Màu sắc <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.mauSac, new { @type = "text", @id = "hinhanh3", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.mauSac, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh4">giá tiền <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.giaGoc, new { @type = "text", @id = "hinhanh4", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.giaGoc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <p class="required">* Phần bắt buộc</p>
            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-9 col-sm-offset-3">
                        <button class="btn btn-success btn-labeled fa fa-check mar-rgt" type="submit" name="luuvanhap">Lưu và nhập sản phẩm</button>
                        <button class="btn btn-mint btn-labeled fa fa-check mar-rgt" type="submit" name="luuvaket">Lưu và kết thúc</button>
                        <a href="@Url.Action("Nhapkho", "Khohang")" class="btn btn-danger btn-labeled fa fa-close">Hủy</a>
                    </div>
                </div>
            </div>
            <!-- END BASIC FORM ELEMENTS -->
        }
    </div>
</div>

BanXeMoTo/BanXeMoTo/Areas/Admin/Views/Khohang/Updatepn.cshtml
@model Models.EF.ThongTinSanPham

@{
    ViewBag.Title = "Cập nhật thông tin sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.NhapSanPham = "active active-link";
}

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Cập nhật thông tin sản phẩm</h3>
    </div>
    <div class="panel-body">
        @if (TempData["AlertMessage"] != null)
        {
            <div id="AlertBox" class="demo-preview-alert hide">
                <div class="alert @TempData["AlertType"] media fade in">
                    <div class="media-body">
                        <h4 class="alert-title">@TempData["AlertMessage"]</h4>
                    </div>
                </div>
            </div>
        }
        @using (Html.BeginForm("Updatepn", "Khohang", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <!-- BASIC FORM ELEMENTS -->
            <div class="panel-body form-horizontal form-padding">
                <div class="form-group">
                    <label class="col-md-3 control-label">Mã Thông tin sản phẩm</label>
                    @Html.TextBoxFor(x => x.maTTSP, new { @type = "hidden", @class = "form-control" })
                    <div class="col-md-9"><p class="form-control-static text-bold">@Model.maTTSP</p></div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="tensp">Tên sản phẩm <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.maSP, ViewBag.ListSanPham as SelectList, new { @class = "selectpicker", @data_live_search = "true", @id = "tensp", @required = "" })
                        @Html.ValidationMessageFor(model => model.maSP, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh1">Số khung <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.soKhung, new { @type = "text", @id = "hinhanh1", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.soKhung, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh2">Số máy <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.soMay, new { @type = "text", @id = "hinhah2", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.soMay, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh3">Màu sắc <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.mauSac, new { @type = "text", @id = "hinhanh3", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.mauSac, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="hinhanh4">giá nhập <span class="required">*</span></label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(x => x.giaGoc, new { @type = "text", @id = "hinhanh4", @class = "form-control", @placeholder = "Nhập tên ảnh sản phẩm", @required = "" })
                        @Html.ValidationMessageFor(x => x.giaGoc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <p class="required">* Phần bắt buộc</p>
            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-9 col-sm-offset-3">
                        <button class="btn btn-success btn-labeled fa fa-check mar-rgt" type="submit">Cập nhật</button>
                        <a href="@Url.Action("Thongtinsanpham", "Sanpham")" class="btn btn-danger btn-labeled fa fa-close">Quay về</a>
                    </div>
                </div>
            </div>
            <!-- END BASIC FORM ELEMENTS -->
        }
    </div>
</div>